# Question 5
a. UPDATE BUSSES SET DESTINATION = 'HOLON' WHERE COMPANY = 'Egged'
b. DROP TABLE PRODUCTS;
c. SELECT BRAND, MODEL, COLOR FROM CARS ORDER BY AMOUNT DESC;
d. DELETE FROM BEVERAGES WHERE VOL = (SELECT max(VOL) FROM BEVERAGES)
e. SELECT ID FROM AIRPLANES JOIN AIRPLANE_ID FROM FLIGHTS on ORDERS.DATE AND ORDERS.DESTINATION AND MODEL.AIRPLANES